//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDA.Resources.Kendo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "████████")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDA.Resources.Kendo.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string BidCreatedOn_Title {
            get {
                return ResourceManager.GetString("BidCreatedOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category_Title {
            get {
                return ResourceManager.GetString("Category_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName_Title {
            get {
                return ResourceManager.GetString("CategoryName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Arabic Name.
        /// </summary>
        public static string CategoryNameAr_Title {
            get {
                return ResourceManager.GetString("CategoryNameAr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category English Name.
        /// </summary>
        public static string CategoryNameEn_Title {
            get {
                return ResourceManager.GetString("CategoryNameEn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string Clickhere_Link {
            get {
                return ResourceManager.GetString("Clickhere_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName_Title {
            get {
                return ResourceManager.GetString("CompanyName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactPersonName_Title {
            get {
                return ResourceManager.GetString("ContactPersonName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of Business.
        /// </summary>
        public static string CorrespondingCategories_Title {
            get {
                return ResourceManager.GetString("CorrespondingCategories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string CR_Title {
            get {
                return ResourceManager.GetString("CR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Number.
        /// </summary>
        public static string CRNumber_Title {
            get {
                return ResourceManager.GetString("CRNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Title {
            get {
                return ResourceManager.GetString("Description_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable this opportunity?.
        /// </summary>
        public static string DisableOpportunityMsg {
            get {
                return ResourceManager.GetString("DisableOpportunityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string DownloadCR {
            get {
                return ResourceManager.GetString("DownloadCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string DownloadProposal {
            get {
                return ResourceManager.GetString("DownloadProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Title {
            get {
                return ResourceManager.GetString("Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to enable this opportunity?.
        /// </summary>
        public static string EnableOpportunityMsg {
            get {
                return ResourceManager.GetString("EnableOpportunityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string FullCompanyName_Title {
            get {
                return ResourceManager.GetString("FullCompanyName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOSI Number.
        /// </summary>
        public static string GOSINumber_Title {
            get {
                return ResourceManager.GetString("GOSINumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string KendoGrid_AddNew {
            get {
                return ResourceManager.GetString("KendoGrid_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string KendoGrid_CustomButtonText {
            get {
                return ResourceManager.GetString("KendoGrid_CustomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string KendoGrid_DeleteButtonText {
            get {
                return ResourceManager.GetString("KendoGrid_DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string KendoGrid_DeleteMessage {
            get {
                return ResourceManager.GetString("KendoGrid_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string KendoGrid_EditButtonText {
            get {
                return ResourceManager.GetString("KendoGrid_EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string KendoGrid_ExportToExcel {
            get {
                return ResourceManager.GetString("KendoGrid_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To PDF.
        /// </summary>
        public static string KendoGrid_ExportToPDF {
            get {
                return ResourceManager.GetString("KendoGrid_ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string KendoGrid_ViewButtonText {
            get {
                return ResourceManager.GetString("KendoGrid_ViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile_Title {
            get {
                return ResourceManager.GetString("Mobile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Employees.
        /// </summary>
        public static string NumberOfEmployees_Title {
            get {
                return ResourceManager.GetString("NumberOfEmployees_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Related RFPs.
        /// </summary>
        public static string NumberOfRelatedRFPs_Title {
            get {
                return ResourceManager.GetString("NumberOfRelatedRFPs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Related SMEs.
        /// </summary>
        public static string NumberOfRelatedSMEs_Title {
            get {
                return ResourceManager.GetString("NumberOfRelatedSMEs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string OneLineDescription_Title {
            get {
                return ResourceManager.GetString("OneLineDescription_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Title.
        /// </summary>
        public static string OpportunityTitle_Title {
            get {
                return ResourceManager.GetString("OpportunityTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants_Title {
            get {
                return ResourceManager.GetString("Participants_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string PersonName_Title {
            get {
                return ResourceManager.GetString("PersonName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor&apos;s Phone.
        /// </summary>
        public static string PhoneNumber_Title {
            get {
                return ResourceManager.GetString("PhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/ service type.
        /// </summary>
        public static string Productservice_Title {
            get {
                return ResourceManager.GetString("Productservice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string Proposal_Title {
            get {
                return ResourceManager.GetString("Proposal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity/ Unit.
        /// </summary>
        public static string QuantityUnit_Title {
            get {
                return ResourceManager.GetString("QuantityUnit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        public static string ReferenceNumber_Title {
            get {
                return ResourceManager.GetString("ReferenceNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Number.
        /// </summary>
        public static string RegistrationNumber_Title {
            get {
                return ResourceManager.GetString("RegistrationNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RequestDateTime_Title {
            get {
                return ResourceManager.GetString("RequestDateTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string RequestType_Title {
            get {
                return ResourceManager.GetString("RequestType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string RFPEndDate_Title {
            get {
                return ResourceManager.GetString("RFPEndDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFP #.
        /// </summary>
        public static string RFPNumber_Title {
            get {
                return ResourceManager.GetString("RFPNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string RFPStartDate_Title {
            get {
                return ResourceManager.GetString("RFPStartDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SME Name.
        /// </summary>
        public static string SMEName_Title {
            get {
                return ResourceManager.GetString("SMEName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status_Title {
            get {
                return ResourceManager.GetString("Status_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Title.
        /// </summary>
        public static string Title_Title {
            get {
                return ResourceManager.GetString("Title_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice_Title {
            get {
                return ResourceManager.GetString("TotalPrice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total RFPs.
        /// </summary>
        public static string TotalRFPs_Title {
            get {
                return ResourceManager.GetString("TotalRFPs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Number.
        /// </summary>
        public static string TransactionNumber_Title {
            get {
                return ResourceManager.GetString("TransactionNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID.
        /// </summary>
        public static string UnifiedNumber_Title {
            get {
                return ResourceManager.GetString("UnifiedNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        public static string VATNumber_Title {
            get {
                return ResourceManager.GetString("VATNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewFullRFP {
            get {
                return ResourceManager.GetString("ViewFullRFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Full RFP.
        /// </summary>
        public static string ViewFullRFP_Header {
            get {
                return ResourceManager.GetString("ViewFullRFP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View RFP Applications.
        /// </summary>
        public static string ViewRFPsApplications {
            get {
                return ResourceManager.GetString("ViewRFPsApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string WantToApply {
            get {
                return ResourceManager.GetString("WantToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Now.
        /// </summary>
        public static string WantToApply_Header {
            get {
                return ResourceManager.GetString("WantToApply_Header", resourceCulture);
            }
        }
    }
}
