//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrailDetail
    {
        public int Id { get; set; }
        public int AuditTrailId { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string AuditMessage { get; set; }
    
        public virtual AuditTrail AuditTrail { get; set; }
    }
}
