//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditTrail()
        {
            this.AuditTrailDetails = new HashSet<AuditTrailDetail>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ModuleName { get; set; }
        public string PageName { get; set; }
        public string TableName { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
        public int ActionTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditTrailDetail> AuditTrailDetails { get; set; }
    }
}
