//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignEntry
    {
        public int Id { get; set; }
        public int CampaignId { get; set; }
        public string CIF { get; set; }
        public decimal Balance { get; set; }
        public int Chances { get; set; }
        public bool IsWithdrawn { get; set; }
        public Nullable<System.DateTime> WithdrawnOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
