//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SSSFramework.DB;
    
    public partial class DDAEntities : SSSProcessDBContext
    {
        public DDAEntities()
            : base("name=DDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<AuditTrailDetail> AuditTrailDetails { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LookUpCategory> LookUpCategories { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CampaignEntry> CampaignEntries { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
    }
}
