//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        public int Id { get; set; }
        public string NameAR { get; set; }
        public string NameEN { get; set; }
        public string UserName { get; set; }
        public string JobTitle { get; set; }
        public string EmployeeNumber { get; set; }
        public string EMail { get; set; }
        public string Phone { get; set; }
        public string PictureUrl { get; set; }
        public Nullable<int> BrancheId { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public bool IsActive { get; set; }
        public string Source { get; set; }
        public string Code { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}
